# Generated by Django 4.1.7 on 2023-04-03 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akkuyu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_name', models.CharField(max_length=255)),
                ('signer_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'akkuyu_nuclear',
            },
        ),
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_name', models.CharField(max_length=10)),
                ('object_place', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'construction_table',
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('signer_name', models.PositiveSmallIntegerField()),
                ('object_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rficrud.construction')),
            ],
            options={
                'db_table': 'concractor',
            },
        ),
        migrations.CreateModel(
            name='QAQC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qa_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'qa_qc_table',
            },
        ),
        migrations.CreateModel(
            name='RFI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('excel_number', models.CharField(max_length=6)),
                ('rfi_number_from_akkuyu', models.CharField(max_length=255)),
                ('date_of_create', models.DateTimeField()),
                ('date_of_inspection', models.DateTimeField()),
                ('object_place', models.CharField(max_length=500)),
                ('project', models.CharField(max_length=255)),
                ('type_of_work', models.CharField(max_length=255)),
                ('description_of_work_russian', models.TextField(blank=True)),
                ('description_of_work_english', models.TextField(blank=True)),
                ('quality_plan_code', models.CharField(max_length=255)),
                ('akkuyu_signer', models.CharField(max_length=255)),
                ('independent_control', models.CharField(blank=True, max_length=255)),
                ('qc_signer', models.CharField(blank=True, max_length=255)),
                ('design_supervision_signer', models.CharField(blank=True, max_length=255)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rficrud.contractor')),
                ('contractor_sintek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_sintek', to='rficrud.contractor')),
                ('object_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rficrud.construction')),
            ],
            options={
                'db_table': 'rfi_table',
            },
        ),
        migrations.CreateModel(
            name='QC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('signer_name', models.CharField(max_length=200)),
                ('object_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rficrud.construction')),
            ],
            options={
                'db_table': 'qc_signer',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('constriction', models.CharField(max_length=5)),
                ('code', models.PositiveSmallIntegerField()),
                ('type_of_works', models.CharField(max_length=2)),
                ('project_name', models.CharField(max_length=10)),
                ('object_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rficrud.construction')),
            ],
            options={
                'db_table': 'project_table',
            },
        ),
        migrations.CreateModel(
            name='IndependentControl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('signer_name', models.CharField(max_length=200)),
                ('object_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rficrud.construction')),
            ],
            options={
                'db_table': 'independent_control',
            },
        ),
        migrations.CreateModel(
            name='DesignerSupervision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('signer_name', models.CharField(max_length=200)),
                ('object_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rficrud.construction')),
            ],
            options={
                'db_table': 'designer_supervision',
            },
        ),
    ]
