# Generated by Django 4.1.7 on 2023-04-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='constriction',
            new_name='constriction_object',
        ),
        migrations.AlterField(
            model_name='contractor',
            name='signer_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='object_place',
            field=models.CharField(max_length=200),
        ),
    ]
