# Generated by Django 4.1.7 on 2023-04-04 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0002_rename_constriction_project_constriction_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfi',
            name='akkuyu_signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rficrud.akkuyu'),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='design_supervision_signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rficrud.designersupervision'),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='independent_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rficrud.independentcontrol'),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='qc_signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rficrud.qc'),
        ),
    ]
