# Generated by Django 4.1.7 on 2023-04-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0003_alter_rfi_akkuyu_signer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfi',
            name='status',
            field=models.CharField(choices=[(-1, 'rejected'), (1, 'accepted'), (2, 'in process'), (3, 'canceled'), (0, 'waiting for status')], default=0, max_length=20),
        ),
    ]
