# Generated by Django 4.1.7 on 2023-04-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0005_remove_rfi_object_place_alter_rfi_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proverka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proverka', models.CharField(max_length=100)),
            ],
        ),
    ]
