# Generated by Django 4.1.7 on 2023-04-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0006_proverka'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proverka',
        ),
    ]
