# Generated by Django 4.1.7 on 2023-04-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0013_alter_rfi_test_rfi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation_construction_test',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
