# Generated by Django 4.1.7 on 2023-04-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0014_alter_relation_construction_test_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfi',
            name='rfi_number_from_akkuyu',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
