# Generated by Django 4.1.7 on 2023-04-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0015_alter_rfi_rfi_number_from_akkuyu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation_construction_test',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
