# Generated by Django 4.1.7 on 2023-04-10 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0016_alter_relation_construction_test_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfi',
            name='test_rfi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rficrud.relation_construction_test'),
        ),
    ]
