# Generated by Django 4.1.7 on 2023-04-11 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0018_alter_rfi_test_rfi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfi',
            name='contractor_sintek',
            field=models.ForeignKey(blank=True, default='Серкан Кандемир  / Serkan Kandemir', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_sintek', to='rficrud.contractor'),
        ),
        migrations.CreateModel(
            name='RelationSupervisionRFI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(max_length=200)),
                ('construction_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rficrud.construction')),
            ],
        ),
        migrations.CreateModel(
            name='RelationQaSignerRFI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(max_length=200)),
                ('construction_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rficrud.construction')),
            ],
        ),
        migrations.CreateModel(
            name='RelationIndependentRFI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(max_length=200)),
                ('construction_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rficrud.construction')),
            ],
        ),
        migrations.CreateModel(
            name='RelationAkkuyuRFI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akkuyu_signer_name', models.CharField(max_length=200)),
                ('constraction_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rficrud.construction')),
            ],
            options={
                'verbose_name': 'Akkuyu Signer',
            },
        ),
        migrations.AlterField(
            model_name='rfi',
            name='akkuyu_signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rficrud.relationakkuyurfi'),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='design_supervision_signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rficrud.relationsupervisionrfi'),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='independent_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rficrud.relationindependentrfi'),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='qc_signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rficrud.relationqasignerrfi'),
        ),
    ]
