# Generated by Django 4.1.7 on 2023-04-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0019_alter_rfi_contractor_sintek_relationsupervisionrfi_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Relation_Construction_Test',
            new_name='RelationConstructionProject',
        ),
    ]
