# Generated by Django 4.1.7 on 2023-04-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0020_rename_relation_construction_test_relationconstructionproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='object_name',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='constriction_object',
            field=models.CharField(default='AKU', max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='type_of_works',
            field=models.CharField(choices=[('AR', 'AR'), ('AS', 'AS')], max_length=2),
        ),
    ]
