# Generated by Django 4.1.7 on 2023-04-11 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0021_alter_construction_object_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfi',
            name='project',
        ),
        migrations.RemoveField(
            model_name='rfi',
            name='test_rfi',
        ),
        migrations.AddField(
            model_name='rfi',
            name='project_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rficrud.relationconstructionproject'),
        ),
    ]
