# Generated by Django 4.1.7 on 2023-04-11 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0022_remove_rfi_project_remove_rfi_test_rfi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationconstructionproject',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rficrud.project'),
        ),
    ]
