# Generated by Django 4.1.7 on 2023-04-12 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0023_alter_relationconstructionproject_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityPlanNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quality_plan_name', models.CharField(max_length=100)),
                ('description_of_work', models.CharField(blank=True, max_length=500, null=True)),
                ('status_of_control_points', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'qa_qc_table',
            },
        ),
        migrations.DeleteModel(
            name='QAQC',
        ),
        migrations.AddField(
            model_name='project',
            name='quality_plan',
            field=models.ForeignKey(default='AKU.2008.00UKU.0.CS.DZ0005_C01', on_delete=django.db.models.deletion.CASCADE, to='rficrud.qualityplannumber'),
        ),
    ]
