# Generated by Django 4.1.7 on 2023-04-12 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0025_alter_qualityplannumber_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='quality_plan',
            field=models.ForeignKey(blank=True, default='AKU.2008.00UKU.0.CS.DZ0005_C01', null=True, on_delete=django.db.models.deletion.CASCADE, to='rficrud.qualityplannumber'),
        ),
        migrations.AlterField(
            model_name='qualityplannumber',
            name='quality_plan_name',
            field=models.CharField(default='AKU.2008.00UKU.0.CS.DZ0005_C01', max_length=100),
        ),
    ]
