# Generated by Django 4.1.7 on 2023-04-24 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0028_alter_project_type_of_works'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfi',
            name='akkuyu_signer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rficrud.relationakkuyurfi'),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='contractor_sintek',
            field=models.CharField(blank=True, default='Серкан Кандемир / Serkan Kandemir \n+90 (552) 505-93-68', max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='design_supervision_signer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rficrud.relationsupervisionrfi'),
        ),
    ]
