# Generated by Django 4.1.7 on 2023-04-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0030_alter_contractor_signer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='contractor_sintek',
            field=models.CharField(blank=True, default='Серкан Кандемир / Serkan Kandemir +90 (552) 505-93-68', max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='type_of_work',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
