# Generated by Django 4.1.7 on 2023-05-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0032_alter_project_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfi',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200, null=True, unique=True),
        ),
    ]
