# Generated by Django 4.1.7 on 2023-05-08 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0033_rfi_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SintekInspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'inspector_table',
            },
        ),
        migrations.AddField(
            model_name='rfi',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfi',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rficrud.sintekinspector'),
        ),
    ]
