# Generated by Django 4.1.7 on 2023-05-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0036_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type_of_works',
            field=models.CharField(choices=[('AR', 'AR'), ('AS', 'AS'), ('KZ', 'KZ'), ('KM', 'KM'), ('TM', 'TM')], max_length=2),
        ),
    ]
