# Generated by Django 4.1.7 on 2023-05-13 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0039_ptoengineer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityplannumber',
            name='quality_plan_name',
            field=models.CharField(default='AKU.2008.00UKU.0.CS.QA0005_C01', max_length=100),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='akkuyu_signer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rficrud.relationakkuyurfi', verbose_name='Представитель заказчика на инспекции'),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rficrud.contractor', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='contractor_sintek',
            field=models.CharField(blank=True, default='Серкан Кандемир / Serkan Kandemir +90 (552) 505-93-68', max_length=220, null=True, verbose_name='Исполнитель Синтек'),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='date_of_create',
            field=models.DateTimeField(verbose_name='Дата и Время создания'),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='date_of_inspection',
            field=models.DateTimeField(verbose_name='Дата и Время проведения комиссии'),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='description_of_work_english',
            field=models.TextField(blank=True, verbose_name='Описание работы на английском'),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='description_of_work_russian',
            field=models.TextField(blank=True, verbose_name='Описание работы на русском'),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='design_supervision_signer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rficrud.relationsupervisionrfi', verbose_name='Авторский надзор'),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='excel_number',
            field=models.CharField(max_length=6, verbose_name='Номер из таблицы эксель'),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='independent_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rficrud.relationindependentrfi', verbose_name='Независимный контроль'),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rficrud.inspector', verbose_name='Инспектор проводящий комиссию'),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='is_active_beton',
            field=models.BooleanField(default=False, help_text='Бетонирование', verbose_name='Бетонирование'),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='object_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rficrud.construction', verbose_name='Строительный Объект'),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='project_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rficrud.project', verbose_name='Имя Проекта'),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='qc_signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rficrud.relationqasignerrfi', verbose_name='Представитель Титан2/ДжейВИ'),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='rfi_number_from_akkuyu',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер ЗНО'),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('accepted', 'accepted'), ('in process', 'in process'), ('canceled', 'canceled'), ('waiting for status', 'waiting for status')], default='waiting for status', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='type_of_work',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип работ'),
        ),
    ]
