# Generated by Django 4.1.7 on 2023-05-16 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0040_alter_qualityplannumber_quality_plan_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfi',
            name='type_of_works',
            field=models.CharField(blank=True, choices=[('Kaynak', 'H-H-W-W'), ('Kaynak', 'H-H-R-R'), ('Pointing', 'H-H-W-R'), ('Demir', 'H-H-H-H'), ('Kalip', 'H-H-H-H'), ('Default', 'H-W-W-W')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='excel_number',
            field=models.CharField(max_length=6, verbose_name='Эксель №'),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='object_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rficrud.construction', verbose_name='Объект'),
        ),
    ]
