# Generated by Django 4.1.7 on 2023-05-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0042_alter_rfi_type_of_works'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfi',
            name='type_of_works',
        ),
        migrations.AddField(
            model_name='rfi',
            name='pk_points',
            field=models.CharField(blank=True, choices=[('H-H-W-W', 'H-H-W-W'), ('H-H-R-R', 'H-H-R-R'), ('H-H-W-R', 'H-H-W-R'), ('H-H-H-H', 'H-H-H-H'), ('H-W-W-W', 'H-W-W-W')], max_length=8, null=True, verbose_name='Точки из плана качества'),
        ),
    ]
