# Generated by Django 4.1.7 on 2023-05-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0043_remove_rfi_type_of_works_rfi_pk_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='checklists_copies',
            field=models.IntegerField(choices=[(0, 'Zero'), (1, 'One')], default=0, verbose_name='Количество копий Чеклистов'),
        ),
        migrations.AddField(
            model_name='inspector',
            name='rfi_copies',
            field=models.IntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two')], default=0, verbose_name='Количество копий ЗНО'),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='pk_points',
            field=models.CharField(blank=True, choices=[('H-H-W-W', 'H-H-W-W'), ('H-H-R-R', 'H-H-R-R'), ('H-H-W-R', 'H-H-W-R'), ('H-H-H-H', 'H-H-H-H'), ('H-W-W-W', 'H-W-W-W')], default='H-H-H-H', max_length=8, null=True, verbose_name='Точки из плана качества'),
        ),
    ]
