# Generated by Django 4.1.7 on 2023-05-24 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0044_inspector_checklists_copies_inspector_rfi_copies_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='construction',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AlterModelOptions(
            name='contractor',
            options={'verbose_name': 'Исполнитель работ', 'verbose_name_plural': 'Исполнитель работ Титан2'},
        ),
        migrations.AlterModelOptions(
            name='inspector',
            options={'verbose_name': 'Инспектор', 'verbose_name_plural': 'Инспекторы'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='ptoengineer',
            options={'verbose_name': 'Инженер ПТО', 'verbose_name_plural': 'Инженеры ПТО'},
        ),
        migrations.AlterModelOptions(
            name='qualityplannumber',
            options={'verbose_name': 'План качества', 'verbose_name_plural': 'Планы качества'},
        ),
        migrations.AlterModelOptions(
            name='relationakkuyurfi',
            options={'verbose_name': 'Представитель Аккую', 'verbose_name_plural': 'Представители Аккую'},
        ),
        migrations.AlterModelOptions(
            name='relationindependentrfi',
            options={'verbose_name': 'Независимый контроль', 'verbose_name_plural': 'Независимый контроль'},
        ),
        migrations.AlterModelOptions(
            name='relationqasignerrfi',
            options={'verbose_name': 'Представитель Титан2/ДжейВИ', 'verbose_name_plural': 'Представители Титан2/ДжейВИ'},
        ),
        migrations.AlterModelOptions(
            name='relationsupervisionrfi',
            options={'verbose_name': 'Авторский надзор', 'verbose_name_plural': 'Авторский надзор'},
        ),
        migrations.AlterModelOptions(
            name='rfi',
            options={'verbose_name': 'ЗНО', 'verbose_name_plural': 'Список ЗНО'},
        ),
        migrations.CreateModel(
            name='DefualtSignersbyConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akkuyy_signer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rficrud.akkuyu', verbose_name='Name of akkuyu signer')),
                ('independent_signer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rficrud.independentcontrol', verbose_name='Name of independent signer')),
                ('object_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rficrud.construction', verbose_name='Name of construction')),
                ('supervision_signer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rficrud.designersupervision', verbose_name='Name of Designer signer')),
                ('titan2_contractor_signer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rficrud.contractor', verbose_name='Name of Contractor signer')),
                ('titan2_qc_signer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rficrud.qc', verbose_name='Name of QC signer')),
            ],
        ),
    ]
