# Generated by Django 4.1.7 on 2023-05-24 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0045_alter_construction_options_alter_contractor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defualtsignersbyconstruction',
            name='akkuyy_signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rficrud.relationakkuyurfi', verbose_name='Name of akkuyu signer'),
        ),
        migrations.AlterField(
            model_name='defualtsignersbyconstruction',
            name='independent_signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rficrud.relationindependentrfi', verbose_name='Name of independent signer'),
        ),
        migrations.AlterField(
            model_name='defualtsignersbyconstruction',
            name='supervision_signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rficrud.relationsupervisionrfi', verbose_name='Name of Designer signer'),
        ),
        migrations.AlterField(
            model_name='defualtsignersbyconstruction',
            name='titan2_qc_signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rficrud.relationqasignerrfi', verbose_name='Name of QC signer'),
        ),
    ]
