# Generated by Django 4.1.7 on 2023-05-24 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0046_alter_defualtsignersbyconstruction_akkuyy_signer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefualtSignersbyConstruction',
            new_name='DefaultSignersbyConstruction',
        ),
        migrations.AlterModelTable(
            name='defaultsignersbyconstruction',
            table='rficrud_defaultsignersbyconstruction',
        ),
    ]
