# Generated by Django 4.1.7 on 2023-05-24 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0047_rename_defualtsignersbyconstruction_defaultsignersbyconstruction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationakkuyurfi',
            old_name='akkuyu_signer_name',
            new_name='signer_name',
        ),
    ]
