# Generated by Django 4.1.7 on 2023-06-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0050_alter_defaultsignersbyconstruction_object_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfi',
            name='inspector',
        ),
        migrations.AlterField(
            model_name='rfi',
            name='status',
            field=models.CharField(choices=[('rejected', 'отказ'), ('accepted', 'accepted'), ('in process', 'in process'), ('canceled', 'canceled'), ('waiting for status', 'Ожидание')], default='waiting for status', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='rfi',
            name='inspector',
            field=models.ManyToManyField(to='rficrud.inspector', verbose_name='Инспектор проводящий комиссию'),
        ),
    ]
