# Generated by Django 4.1.7 on 2023-06-06 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rficrud', '0051_remove_rfi_inspector_alter_rfi_status_rfi_inspector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfi',
            name='inspector',
        ),
        migrations.AddField(
            model_name='rfi',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rficrud.inspector', verbose_name='Инспектор проводящий комиссию'),
        ),
    ]
